### ISSUE TITLE
unknow feedback

### ISSUE THREAD

**Issue by Sylvain-Yu** [swim2sun/migu-music-dl#2]
![image](https://user-images.githubusercontent.com/33903910/156113342-9a906a21-5298-412d-b626-56555749851c.png)

**Comment by swim2sun** [comment]
升级一下python版本，3.8或以上的版本

**Comment by WellingtonMonteiro** [comment]
![Screenshot_20220313-075208](https://user-images.githubusercontent.com/31768953/158056121-4ead65e1-bcff-455f-95e5-4a67e9cfdae5.png)

**Comment by swim2sun** [comment]
released Rust version: <https://github.com/swim2sun/migu-music-dl/releases/tag/app-v0.1.0>
